### PR TITLE
30 remove iset history and jset history from tensorci2

### PR DESCRIPTION
**Pull request by shinaoka**
* Remove `history` from TCI2.
* Unified implementation for adding external global pivots and internal global pivots

### CODE REVIEW

**Comment by rittermarc** [comment]
I think this is good logic, and I didn't find any problems testing it. I would like to clean up some of the new documentation & error messages though, should I just change these myself?

**Comment by shinaoka** [comment]
As I wrote to you by e-mail, I have a different new idea. Let us first check the new one before merging this PR.

**Comment by shinaoka** [comment]
@rittermarc 
Let us merge this into the main branch. Do you want to still edit the branch yourself?

**Comment by shinaoka** [comment]
This approach is not the way to go, as we discussed on Zoom.

**Pull request closed without merging**
